-- Seed Data for Prescripta Database
-- 48 Error Codes + Sample BNF Categories + Severity Matrix

-- ===========================================
-- ERROR CODES (48 total)
-- ===========================================

-- Paraphrase Flags (44)
INSERT INTO error_codes (code, description) VALUES
('DRUG_NAME_IN_DIRECTION', 'Drug name appears in dosage directions (should not)'),
('DISPENSING_TEXT_IN_DIRECTION', 'Dispensing/supply text leaked into dosage directions'),
('ADMIN_VERB_ASSUMED', 'Administration verb introduced that was not present'),
('ADMIN_VERB_ALTERED', 'Administration verb changed'),
('ADMIN_VERB_OMITTED', 'Administration verb omitted'),
('DOSE_ASSUMED', 'Dose amount/pattern introduced that was not present'),
('DOSE_ALTERED', 'Dose amount/pattern changed'),
('DOSE_OMITTED', 'Dose amount/pattern omitted'),
('STRENGTH_ASSUMED', 'Strength introduced that was not present'),
('STRENGTH_ALTERED', 'Strength changed'),
('STRENGTH_OMITTED', 'Strength omitted when present'),
('FREQUENCY_ASSUMED', 'Frequency schedule/constraint introduced'),
('FREQUENCY_ALTERED', 'Frequency schedule/constraint changed'),
('FREQUENCY_OMITTED', 'Frequency schedule/constraint omitted'),
('FORM_ASSUMED', 'Medication form/unit word introduced'),
('FORM_ALTERED', 'Medication form/unit word changed'),
('FORM_OMITTED', 'Medication form/unit word omitted'),
('SITE_ASSUMED', 'Body site introduced that was not present'),
('SITE_ALTERED', 'Body site changed'),
('SITE_OMITTED', 'Required body site omitted'),
('PRN_ASSUMED', 'PRN/when required introduced when not present'),
('PRN_ALTERED', 'PRN meaning changed'),
('PRN_OMITTED', 'PRN omitted (becomes scheduled)'),
('INDICATION_ASSUMED', 'Indication/symptom introduced'),
('INDICATION_ALTERED', 'Indication/symptom changed'),
('INDICATION_OMITTED', 'Indication/symptom omitted'),
('MAX_DOSE_ASSUMED', 'Maximum dose limit introduced'),
('MAX_DOSE_ALTERED', 'Maximum dose limit changed'),
('MAX_DOSE_OMITTED', 'Maximum dose limit omitted'),
('MAX_PERIOD_ASSUMED', 'Max-dose time window introduced'),
('MAX_PERIOD_ALTERED', 'Max-dose time window changed'),
('MAX_PERIOD_OMITTED', 'Max-dose time window omitted'),
('INSTRUCTION_ASSUMED', 'Additional instruction text introduced'),
('INSTRUCTION_ALTERED', 'Instruction meaning changed'),
('INSTRUCTION_OMITTED', 'Instruction text omitted'),
('DURATION_ASSUMED', 'Course length introduced'),
('DURATION_ALTERED', 'Course length changed'),
('DURATION_OMITTED', 'Course length omitted'),
('LATIN_CODE_UNEXPANDED', 'Latin/abbrev code left unexpanded'),
('LATIN_CODE_MISINTERPRETED', 'Latin/abbrev code expanded incorrectly'),
('LATIN_CODE_ASSUMED', 'Latin/abbrev meaning introduced where none existed'),
('SPELLING_ERROR', 'Spelling/typo error reduces clarity'),
('ORIGINAL_DOSAGE_UNCLEAR', 'Original dosage direction too unclear to translate'),
('UNSUPPORTED_SYNTAX', 'Instruction too complex; meaning lost or distorted');

-- Safety Flags (3)
INSERT INTO error_codes (code, description) VALUES
('DOSAGE_CHECK_OVERDOSE', 'Prescribed dose exceeds maximum limit'),
('DOSAGE_CHECK_UNDERDOSE', 'Prescribed dose below minimum limit'),
('DOSAGE_CHECK_INCONCLUSIVE', 'Unable to determine if dose is safe');

-- Explicit Review Flag (1)
INSERT INTO error_codes (code, description) VALUES
('PHARMACIST_REVIEW_REQUESTED', 'Explicit review requested by prescriber');


-- ===========================================
-- BNF CATEGORIES (from provided list)
-- ===========================================

INSERT INTO bnf_categories (code, name, parent_code) VALUES
('10101', 'Antacids and simeticone', NULL),
('10102', 'Compound alginates and proprietary indigestion preparations', NULL),
('10200', 'Antispasmodics and other drugs altering gut motility', NULL),
('10301', 'H2 - receptor antagonists', NULL),
('10303', 'Chelates and complexes', NULL),
('10304', 'Prostaglandin analogues', NULL),
('10305', 'Proton pump inhibitors', NULL),
('10401', 'Adsorbents and bulk-forming drugs', NULL),
('10402', 'Antimotility drugs', NULL),
('10500', 'Chronic bowel disorders', NULL),
('10501', 'Aminosalicylates', NULL),
('10502', 'Corticosteroids', NULL),
('10601', 'Bulk forming laxatives', NULL),
('10602', 'Stimulant laxatives', NULL),
('10603', 'Faecal softeners', NULL),
('10604', 'Osmotic laxatives', NULL),
('10605', 'Bowel cleansing solutions', NULL),
('10701', 'Soothing haemorrhoidal preparations', NULL),
('10702', 'Compound haemorrhoidal preparations with corticosteroids', NULL),
('10704', 'Management of anal fissures', NULL),
('10800', 'Stoma care', NULL),
('10901', 'Drugs affecting biliary composition and flow', NULL),
('10904', 'Pancreatin', NULL),
('20101', 'Cardiac glycosides', NULL),
('20201', 'Phosphodiesterase inhibitors', NULL),
('20202', 'Loop diuretics', NULL),
('20203', 'Potassium-sparing diuretics and aldosterone antagonists', NULL),
('20204', 'Potassium-sparing diuretics with other diuretics', NULL),
('20208', 'Diuretics with potassium', NULL),
('20301', 'Management of arrhythmias', NULL),
('20302', 'Drugs for arrhythmias', NULL),
('20400', 'Beta-adrenoceptor blocking drugs', NULL),
('20501', 'Vasodilator antihypertensive drugs', NULL),
('20502', 'Centrall acting antihypertensive drugs', NULL),
('20504', 'Alpha-adrenoceptor blocking drugs', NULL),
('20505', 'Drugs affecting the renin-angiotensin system', NULL),
('20601', 'Nitrates', NULL),
('20602', 'Calcium-channel blockers', NULL),
('20603', 'Other antianginal drugs', NULL),
('20604', 'Peripheral vasodilators and related drugs', NULL),
('20703', 'Cardiopulmonary resuscitation', NULL),
('20801', 'Parental anticoagulants', NULL),
('20802', 'Oral anticoagulants', NULL),
('20900', 'Antiplatelet drugs', NULL),
('21001', 'Management of myocardial infarction', NULL),
('21100', 'Antifibrinolytic drugs and haemostatics', NULL),
('21200', 'Lipid-regulating drugs', NULL),
('30100', 'Bronchodilators', NULL),
('30101', 'Adrenoceptor agonists', NULL),
('30102', 'Antimuscarinic bronchodilators', NULL),
('30103', 'Theophylline', NULL),
('30104', 'Compound bronchodilator preparations', NULL),
('30105', 'Peak flow meters, inhaler devices and nebulisers', NULL),
('30200', 'Corticosteroids', NULL),
('30301', 'Cromoglicate and related therapy', NULL),
('30302', 'Leukotriene receptor antagonists', NULL),
('30401', 'Antihistamines', NULL),
('30403', 'Allergic emergencies', NULL),
('30600', 'Oxygen', NULL),
('30700', 'Mucolytics', NULL),
('30800', 'Aromatic inhalations', NULL),
('30901', 'Cough suppressants', NULL),
('30902', 'Expectorant and demulcent cough preparations', NULL),
('31000', 'Systemic nasal decongestants', NULL),
('40101', 'Hypnotics', NULL),
('40102', 'Anxiolytics', NULL),
('40103', 'Barbiturates', NULL),
('40201', 'Antipsychotic drugs', NULL),
('40202', 'Antipsychotic depot injections', NULL),
('40203', 'Antimanic drugs', NULL),
('40300', 'Antidepressant drugs', NULL),
('40301', 'Tricyclic and related antidepressant drugs', NULL),
('40302', 'Monoamine-oxidase inhibitors', NULL),
('40303', 'Selective serotonin re-uptake inhibitors', NULL),
('40304', 'Other antidepressant drugs', NULL),
('40400', 'CNS stimulatns and drugs used for ADHD', NULL),
('40501', 'Anti-obesity drugs acting on the gastro-intestinal tract', NULL),
('40600', 'Drugs used in nausea and vertigo', NULL),
('40700', 'Analgesics', NULL),
('40701', 'Non-opioid analgesics', NULL),
('40702', 'Opioid analgesics', NULL),
('40704', 'Antimigraine drugs', NULL),
('40801', 'Control of epilepsy', NULL),
('40802', 'Drugs used in status epilepticus', NULL),
('40901', 'Dopaminergic drugs used in parkinsonism', NULL),
('40902', 'Antimuscarinic drugs used in parkinsonism', NULL),
('40903', 'Drugs used in essential termor, chorea, tics and related disorders', NULL),
('41000', 'Drugs used in substance dependence', NULL),
('41100', 'Drugs for dementia', NULL),
('50100', 'Antibacterial drugs', NULL),
('50101', 'Penicillins', NULL),
('50102', 'Cephalosporins and other betalactams', NULL),
('50103', 'Tetracyclines', NULL),
('50104', 'Aminoglycosides', NULL),
('50105', 'Macrolides', NULL),
('50106', 'Clindamycin', NULL),
('50107', 'Some other antibacterials', NULL),
('50108', 'Sulphonamides and trimethoprim', NULL),
('50109', 'Antituberculosis drugs', NULL),
('50110', 'Antileprotic drugs', NULL),
('50111', 'Metronidazole and tinidazole', NULL),
('50112', 'Quinolones', NULL),
('50113', 'Urinary-tract infections', NULL),
('50200', 'Antifungal drugs', NULL),
('50301', 'HIV injection', NULL),
('50302', 'Herpesvirus infections', NULL),
('50304', 'Influenza', NULL),
('50401', 'Antimalarials', NULL),
('50404', 'Antigiardial drugs', NULL),
('50408', 'Drugs for pneumocystis pneumonia', NULL),
('50501', 'Drugs for threadworms', NULL),
('50503', 'Drugs for tapeworm infections', NULL),
('50506', 'Filaricides', NULL),
('60101', 'Insulins', NULL),
('60102', 'Antidiabetic drugs', NULL),
('60103', 'Diabetic ketoacidosis', NULL),
('60104', 'Treatment of hypoglycaemia', NULL),
('60105', 'Treatment of diabetic nephropathy and neuropathy', NULL),
('60106', 'Diagnostic and monitoring agents for diabetes mellitus', NULL),
('60201', 'Thyroid hormones', NULL),
('60202', 'Antithyroid drugs', NULL),
('60301', 'Replacement therapy', NULL),
('60302', 'Glucocorticoid therapy', NULL),
('60401', 'Female sex hormones', NULL),
('60402', 'Male sex hormones and antagonists', NULL),
('60501', 'Hypothalamic and pituitary hormones and anti-oestrogens', NULL),
('60502', 'Posterior pituitary hormones and antagonists', NULL),
('60601', 'Calcitonin and parathyroid hormone', NULL),
('60602', 'Bisphosphonates and other drugs affecting bone metabolism', NULL),
('60701', 'Bromocriptine and other dopaminergic drugs', NULL),
('60702', 'Drugs affecting gonadotrophins', NULL),
('60703', 'Metyraphone and trilostane', NULL),
('70103', 'Myometrial relaxants', NULL),
('70201', 'Preparations for vaginal atrophy', NULL),
('70202', 'Vaginal and vulval infections', NULL),
('70301', 'Combined hormonal contraceptives', NULL),
('70302', 'Progestogen-only contraceptives', NULL),
('70304', 'Contraceptive devices', NULL),
('70401', 'Drugs for urinary retention', NULL),
('70402', 'Drugs for urinary frequency, enuresis and incontinence', NULL),
('70403', 'Drugs used in urological pain', NULL),
('70404', 'Bladder instillations and urological surgery', NULL),
('70405', 'Drugs for erectile dysfunction', NULL),
('80100', 'Cytotoxic Drugs', NULL),
('80101', 'Alkylating drugs', NULL),
('80103', 'Antimetabolites', NULL),
('80105', 'Other antineoplastic drugs', NULL),
('80201', 'Antiproliferative immunosuppressants', NULL),
('80202', 'Corticosteroids and other immunosuppressants', NULL),
('80204', 'Other immunomodulating drugs', NULL),
('80301', 'Oestrogens', NULL),
('80302', 'Progestogens', NULL),
('80304', 'Hormone antagonists', NULL),
('90101', 'Iron-deficiency anaemias', NULL),
('90102', 'Drugs used in megaloblastic anaemias', NULL),
('90103', 'Drugs used in hypoplastic, haemolytic and renal anaemias', NULL),
('90104', 'Drugs used in platelet disorders', NULL),
('90106', 'Drugs used in neutropenia', NULL),
('90201', 'Oral preparations for fluid and electrolytc imbalance', NULL),
('90202', 'Parenteral preparations for fluid and elctrolytes imbalance', NULL),
('90300', 'Intravenous nutrition', NULL),
('90400', 'Oral nutrition', NULL),
('90401', 'Foods for special diets', NULL),
('90402', 'Enteral nutrition', NULL),
('90500', 'Minerals', NULL),
('90501', 'Calcium and magnesium', NULL),
('90502', 'Phosphorus', NULL),
('90503', 'Fluoride', NULL),
('90504', 'Zinc', NULL),
('90601', 'Vitamin A', NULL),
('90602', 'Vitamin B', NULL),
('90603', 'Vitamin C', NULL),
('90604', 'Vitamin D', NULL),
('90605', 'Vitamin E', NULL),
('90606', 'Vitamin K', NULL),
('90607', 'Multivitamin preparations', NULL),
('90700', 'Bitters and tonics', NULL),
('90801', 'Drugs used in metabolic disorders', NULL),
('100101', 'NSAID', NULL),
('100102', 'Corticosteroids', NULL),
('100103', 'Drugs that suppress the rheumatic disease process', NULL),
('100104', 'Gout and cytotoxic-induced hyperuricaemia', NULL),
('100105', 'Other drugs for rheumatic diseases', NULL),
('100201', 'Drugs that enhance neuromuscular transmission', NULL),
('100202', 'Skeletal muscle relaxants', NULL),
('100300', 'Drugs for the relief of soft-tissue inflammation', NULL),
('100301', 'Enzymes', NULL),
('100302', 'Rubefacients and other topical antirheumatics', NULL),
('110301', 'Antibacterials', NULL),
('110303', 'Antivirals', NULL),
('110401', 'Corticosteroids', NULL),
('110402', 'Other anti-inflammatory preparations', NULL),
('110500', 'Mydriatics and cycloplegics', NULL),
('110600', 'Treatment of glaucoma', NULL),
('110800', 'Miscellaneous ophthalmic preparations', NULL),
('110801', 'Tear deficiency, ocular lubricants and astringents', NULL),
('110802', 'Ocular diagnostic and perioperative preparations and photodynamic treatment', NULL),
('120101', 'Otitis externa', NULL),
('120103', 'Removal of ear wax', NULL),
('120201', 'Drugs used in nasal allergy', NULL),
('120202', 'Topical nasal decongestants', NULL),
('120203', 'Nasal preparations for infection', NULL),
('120300', 'Drugs acting on the oropharynx', NULL),
('120301', 'Drugs for oral ulceration and inflammation', NULL),
('120302', 'Oropharyngeal anti-infective drugs', NULL),
('120303', 'Lozenges and sprays', NULL),
('120304', 'Mouthwashes, gargles and dentifrices', NULL),
('120305', 'Treatment of dry mouth', NULL),
('130000', 'Skin', NULL),
('130103', 'Excipients and sensitisation', NULL),
('130201', 'Emollients', NULL),
('130202', 'Emollient bath additives', NULL),
('130300', 'Topical local anaesthetics and antipruritics', NULL),
('130400', 'Topical corticosteroids', NULL),
('130500', 'Preparations for eczema and psoriasis', NULL),
('130501', 'Preparations for eczema', NULL),
('130502', 'Preparations for psoriasis', NULL),
('130503', 'Drugs affecting the immune response', NULL),
('130601', 'Topical preparations for acne', NULL),
('130602', 'Oral preparations for acne', NULL),
('130700', 'Preparations for warts and calluses', NULL),
('130801', 'Sunscreen preparations', NULL),
('130802', 'Camouflagers', NULL),
('130900', 'Shampoos and other preparations for scalp and hair conditions', NULL),
('131001', 'Antibacterial preparations', NULL),
('131002', 'Antifungal preparations', NULL),
('131003', 'Antiviral preparations', NULL),
('131004', 'Parasiticidal preparations', NULL),
('131005', 'Preparations for minor cuts and abrasions', NULL),
('131100', 'Skin cleansers and antiseptics', NULL),
('131101', 'Alcohols and saline', NULL),
('131102', 'Chlorhexidine salts', NULL),
('131104', 'Iodine', NULL),
('131105', 'Phenolics', NULL),
('131106', 'Oxidisers and dyes', NULL),
('131107', 'Preparations for promotion of wound healing', NULL),
('131200', 'Antiperspirants', NULL),
('131300', 'Topical circulatory preparations', NULL),
('140400', 'Vaccines and antisera', NULL),
('140500', 'Immunoglobulins', NULL),
('150102', 'Inhalational anaesthetics', NULL),
('150103', 'Antimuscarinic drugs', NULL),
('150104', 'Sedative and analgesic perioperative drugs', NULL),
('150200', 'Local Anaesthesia', NULL);


-- ===========================================
-- FLAG SEVERITY INDEX (all BNF × all Error Codes, default RED)
-- ===========================================

INSERT INTO flag_severity (bnf_code, error_code, is_red_flag)
SELECT b.code, e.code, TRUE
FROM bnf_categories b
CROSS JOIN error_codes e;
